### ISSUE TITLE
minItems, maxItems not supported

### ISSUE THREAD

**Issue by liuxh0** [johngeorgewright/runtyping#29]
Generating runtypes from json schema:
```
{
  "title": "Example Schema",
  "type": "object",
  "properties": {
    "testArray": {
      "type": "array",
      "items": {
        "type": "object"
      }
    }
  },
  "additionalProperties": false
}
```
This works.

However adding `minItems` (or `maxItems`) for array:
```
{
  "title": "Example Schema",
  "type": "object",
  "properties": {
    "testArray": {
      "type": "array",
      "minItems": 2,
      "items": {
        "type": "object"
      }
    }
  },
  "additionalProperties": false
}
```
I got error when running `npx rungen`:
```
InvalidOperationError: Expected to find a symbol.
    at Object.throwIfNullOrUndefined (/Users/xliu/workspaces/runtyping/node_modules/@ts-morph/common/dist/ts-morph-common.js:471:19)
    at Type.getSymbolOrThrow (/Users/xliu/workspaces/runtyping/node_modules/ts-morph/dist/ts-morph.js:17388:30)
    at Object.objectTypeGenerator [as default] (/Users/xliu/workspaces/runtyping/dist/typeWriter/object.js:9:10)
    at objectTypeGenerator.next (<anonymous>)
    at Object.generateOrReuseType [as default] (/Users/xliu/workspaces/runtyping/dist/typeWriter/generateOrReuseType.js:12:29)
    at generateOrReuseType.next (<anonymous>)
    at Object.unionTypeGenerator [as default] (/Users/xliu/workspaces/runtyping/dist/typeWriter/union.js:12:41)
    at unionTypeGenerator.next (<anonymous>)
    at Object.generateOrReuseType [as default] (/Users/xliu/workspaces/runtyping/dist/typeWriter/generateOrReuseType.js:12:29)
    at generateOrReuseType.next (<anonymous>)
```

**Comment by johngeorgewright** [comment]
Thanks for raising this. It's still a fairly new project so I expect to have missed a few things. Turns out it doesn't handle tuples yet, which is the root of this problem.
