### ISSUE TITLE
Getting a  "TYPE xxx NOT PARSED" error for a generic type.

### ISSUE THREAD

**Issue by AsPulse** [johngeorgewright/runtyping#398]
### Steps to Reproduce

The minimum code to reproduce the error in the title is :
```ts
type Test<T> = T & { count: number };

export type Foo = {
  abc: Test<{ data: string }>
};
```

I excepted:
```ts
export const Foo = Record({ 
  abc: Record({ data: String }).And(Record({ count: Number }))
});
```

but, I got:
```
       throw new Error('!!! TYPE ' + type.getText() + ' NOT PARSED !!!')
              ^
Error: !!! TYPE T NOT PARSED !!!
    at RuntypesTypeWriters.typeWriter (E:\Persistent\GitHub-Develops\schema\node_modules\@runtyping\generator\src\TypeWriters.ts:102:15)
    at typeWriter.next (<anonymous>)
    at RuntypesTypeWriters.generateOrReuseType (E:\Persistent\GitHub-Develops\schema\node_modules\@runtyping\generator\src\TypeWriters.ts:117:17)
    at generateOrReuseType.next (<anonymous>)
    at RuntypesTypeWriters.union (E:\Persistent\GitHub-Develops\schema\node_modules\@runtyping\runtypes\src\RuntypesTypeWriters.ts:143:17)
    at union.next (<anonymous>)
    at RuntypesTypeWriters.typeWriter (E:\Persistent\GitHub-Develops\schema\node_modules\@runtyping\generator\src\TypeWriters.ts:66:28)
    at typeWriter.next (<anonymous>)
    at IteratorHandler.run (E:\Persistent\GitHub-Develops\schema\node_modules\@johngw\iterator\src\IteratorHandler.ts:65:29)
    at runTypeWriter (E:\Persistent\GitHub-Develops\schema\node_modules\@runtyping\generator\src\Generator.ts:250:10)
```

### Information
`@runtyping/runtypes`: `1.3.1`
`runtypes`: `6.6.0`

**Comment by johngeorgewright** [comment]
I can replicate this too. I'll get on it asap.
